services:
  pgvector:
    image: ankane/pgvector:v0.5.1
    container_name: pgvector
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "/tmp/pgvector_data:/var/lib/postgresql/data"
    deploy:
      resources:
        limits:
          cpus: "8"
        reservations:
          cpus: "4"
